# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainboard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UsartTool(object):
    def setupUi(self, UsartTool):
        UsartTool.setObjectName(_fromUtf8("UsartTool"))
        UsartTool.resize(472, 323)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(UsartTool)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.SerialnumLabel = QtGui.QLabel(UsartTool)
        self.SerialnumLabel.setObjectName(_fromUtf8("SerialnumLabel"))
        self.gridLayout.addWidget(self.SerialnumLabel, 0, 0, 1, 1)
        self.SerialNumComboBox = QtGui.QComboBox(UsartTool)
        self.SerialNumComboBox.setObjectName(_fromUtf8("SerialNumComboBox"))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.SerialNumComboBox, 0, 1, 1, 1)
        self.DataBitsLabel = QtGui.QLabel(UsartTool)
        self.DataBitsLabel.setObjectName(_fromUtf8("DataBitsLabel"))
        self.gridLayout.addWidget(self.DataBitsLabel, 1, 0, 1, 1)
        self.DatabitsComboBox = QtGui.QComboBox(UsartTool)
        self.DatabitsComboBox.setObjectName(_fromUtf8("DatabitsComboBox"))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.DatabitsComboBox, 1, 1, 1, 1)
        self.BaudRateLabel = QtGui.QLabel(UsartTool)
        self.BaudRateLabel.setObjectName(_fromUtf8("BaudRateLabel"))
        self.gridLayout.addWidget(self.BaudRateLabel, 2, 0, 1, 1)
        self.BaudRataComboBox = QtGui.QComboBox(UsartTool)
        self.BaudRataComboBox.setObjectName(_fromUtf8("BaudRataComboBox"))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.BaudRataComboBox, 2, 1, 1, 1)
        self.StopBitsLabel = QtGui.QLabel(UsartTool)
        self.StopBitsLabel.setObjectName(_fromUtf8("StopBitsLabel"))
        self.gridLayout.addWidget(self.StopBitsLabel, 3, 0, 1, 1)
        self.StopBitsComboBox = QtGui.QComboBox(UsartTool)
        self.StopBitsComboBox.setObjectName(_fromUtf8("StopBitsComboBox"))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.StopBitsComboBox, 3, 1, 1, 1)
        self.ParityLabel = QtGui.QLabel(UsartTool)
        self.ParityLabel.setObjectName(_fromUtf8("ParityLabel"))
        self.gridLayout.addWidget(self.ParityLabel, 4, 0, 1, 1)
        self.ParityComboBox = QtGui.QComboBox(UsartTool)
        self.ParityComboBox.setObjectName(_fromUtf8("ParityComboBox"))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.ParityComboBox, 4, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.SwitchButton = QtGui.QPushButton(UsartTool)
        self.SwitchButton.setObjectName(_fromUtf8("SwitchButton"))
        self.verticalLayout_3.addWidget(self.SwitchButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.DataReceiveArea = QtGui.QLabel(UsartTool)
        self.DataReceiveArea.setObjectName(_fromUtf8("DataReceiveArea"))
        self.verticalLayout.addWidget(self.DataReceiveArea)
        self.textEdit = QtGui.QTextEdit(UsartTool)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.DataSendArea = QtGui.QLabel(UsartTool)
        self.DataSendArea.setObjectName(_fromUtf8("DataSendArea"))
        self.verticalLayout_2.addWidget(self.DataSendArea)
        self.DataToSend = QtGui.QLineEdit(UsartTool)
        self.DataToSend.setObjectName(_fromUtf8("DataToSend"))
        self.verticalLayout_2.addWidget(self.DataToSend)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.SendDataButton = QtGui.QPushButton(UsartTool)
        self.SendDataButton.setObjectName(_fromUtf8("SendDataButton"))
        self.horizontalLayout.addWidget(self.SendDataButton)
        self.ClearDataButton = QtGui.QPushButton(UsartTool)
        self.ClearDataButton.setObjectName(_fromUtf8("ClearDataButton"))
        self.horizontalLayout.addWidget(self.ClearDataButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.SwitchButton.raise_()
        self.textEdit.raise_()
        self.DataReceiveArea.raise_()
        self.DataSendArea.raise_()
        self.SendDataButton.raise_()
        self.ClearDataButton.raise_()
        self.DataToSend.raise_()
        self.SerialnumLabel.setBuddy(self.SerialNumComboBox)
        self.DataBitsLabel.setBuddy(self.DatabitsComboBox)
        self.BaudRateLabel.setBuddy(self.BaudRataComboBox)
        self.StopBitsLabel.setBuddy(self.StopBitsComboBox)
        self.ParityLabel.setBuddy(self.ParityComboBox)
        self.DataReceiveArea.setBuddy(self.textEdit)
        self.DataSendArea.setBuddy(self.DataToSend)

        self.retranslateUi(UsartTool)
        QtCore.QMetaObject.connectSlotsByName(UsartTool)

    def retranslateUi(self, UsartTool):
        UsartTool.setWindowTitle(_translate("UsartTool", "Dialog", None))
        self.SerialnumLabel.setText(_translate("UsartTool", "串口号：", None))
        self.SerialNumComboBox.setItemText(0, _translate("UsartTool", "COM1", None))
        self.SerialNumComboBox.setItemText(1, _translate("UsartTool", "COM2", None))
        self.SerialNumComboBox.setItemText(2, _translate("UsartTool", "COM3", None))
        self.SerialNumComboBox.setItemText(3, _translate("UsartTool", "COM4", None))
        self.SerialNumComboBox.setItemText(4, _translate("UsartTool", "COM6", None))
        self.SerialNumComboBox.setItemText(5, _translate("UsartTool", "COM7", None))
        self.DataBitsLabel.setText(_translate("UsartTool", "数据位：", None))
        self.DatabitsComboBox.setItemText(0, _translate("UsartTool", "5", None))
        self.DatabitsComboBox.setItemText(1, _translate("UsartTool", "6", None))
        self.DatabitsComboBox.setItemText(2, _translate("UsartTool", "7", None))
        self.DatabitsComboBox.setItemText(3, _translate("UsartTool", "8", None))
        self.BaudRateLabel.setText(_translate("UsartTool", "波特率：", None))
        self.BaudRataComboBox.setItemText(0, _translate("UsartTool", "4800", None))
        self.BaudRataComboBox.setItemText(1, _translate("UsartTool", "9600", None))
        self.BaudRataComboBox.setItemText(2, _translate("UsartTool", "19200", None))
        self.BaudRataComboBox.setItemText(3, _translate("UsartTool", "57600", None))
        self.BaudRataComboBox.setItemText(4, _translate("UsartTool", "115200", None))
        self.StopBitsLabel.setText(_translate("UsartTool", "停止位：", None))
        self.StopBitsComboBox.setItemText(0, _translate("UsartTool", "1", None))
        self.StopBitsComboBox.setItemText(1, _translate("UsartTool", "1.5", None))
        self.StopBitsComboBox.setItemText(2, _translate("UsartTool", "2", None))
        self.ParityLabel.setText(_translate("UsartTool", "奇偶校验位：", None))
        self.ParityComboBox.setItemText(0, _translate("UsartTool", "N", None))
        self.ParityComboBox.setItemText(1, _translate("UsartTool", "O", None))
        self.ParityComboBox.setItemText(2, _translate("UsartTool", "E", None))
        self.ParityComboBox.setItemText(3, _translate("UsartTool", "M", None))
        self.ParityComboBox.setItemText(4, _translate("UsartTool", "S", None))
        self.SwitchButton.setText(_translate("UsartTool", "打开串口", None))
        self.DataReceiveArea.setText(_translate("UsartTool", "数据接收区域：", None))
        self.DataSendArea.setText(_translate("UsartTool", "数据发送区域：", None))
        self.SendDataButton.setText(_translate("UsartTool", "发送", None))
        self.ClearDataButton.setText(_translate("UsartTool", "清除", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UsartTool = QtGui.QDialog()
    ui = Ui_UsartTool()
    ui.setupUi(UsartTool)
    UsartTool.show()
    sys.exit(app.exec_())

