# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainboard.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_UsartTool(object):
    def setupUi(self, UsartTool):
        UsartTool.setObjectName(_fromUtf8("UsartTool"))
        UsartTool.resize(487, 340)
        self.SwitchButton = QtGui.QPushButton(UsartTool)
        self.SwitchButton.setGeometry(QtCore.QRect(10, 150, 181, 23))
        self.SwitchButton.setObjectName(_fromUtf8("SwitchButton"))
        self.textEdit = QtGui.QTextEdit(UsartTool)
        self.textEdit.setGeometry(QtCore.QRect(200, 40, 261, 201))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.DataReceiveArea = QtGui.QLabel(UsartTool)
        self.DataReceiveArea.setGeometry(QtCore.QRect(200, 10, 84, 31))
        self.DataReceiveArea.setObjectName(_fromUtf8("DataReceiveArea"))
        self.DataSendArea = QtGui.QLabel(UsartTool)
        self.DataSendArea.setGeometry(QtCore.QRect(200, 250, 84, 16))
        self.DataSendArea.setObjectName(_fromUtf8("DataSendArea"))
        self.SendDataButton = QtGui.QPushButton(UsartTool)
        self.SendDataButton.setGeometry(QtCore.QRect(200, 300, 75, 23))
        self.SendDataButton.setObjectName(_fromUtf8("SendDataButton"))
        self.ClearDataButton = QtGui.QPushButton(UsartTool)
        self.ClearDataButton.setGeometry(QtCore.QRect(390, 10, 75, 23))
        self.ClearDataButton.setObjectName(_fromUtf8("ClearDataButton"))
        self.DataToSend = QtGui.QLineEdit(UsartTool)
        self.DataToSend.setGeometry(QtCore.QRect(200, 270, 261, 20))
        self.DataToSend.setObjectName(_fromUtf8("DataToSend"))
        self.HexDisCheckbox = QtGui.QCheckBox(UsartTool)
        self.HexDisCheckbox.setGeometry(QtCore.QRect(300, 10, 65, 31))
        self.HexDisCheckbox.setObjectName(_fromUtf8("HexDisCheckbox"))
        self.MenuButton = QtGui.QPushButton(UsartTool)
        self.MenuButton.setGeometry(QtCore.QRect(70, 240, 61, 31))
        self.MenuButton.setObjectName(_fromUtf8("MenuButton"))
        self.PowerButton = QtGui.QPushButton(UsartTool)
        self.PowerButton.setGeometry(QtCore.QRect(10, 290, 61, 31))
        self.PowerButton.setObjectName(_fromUtf8("PowerButton"))
        self.PlusButton = QtGui.QPushButton(UsartTool)
        self.PlusButton.setGeometry(QtCore.QRect(130, 240, 61, 31))
        self.PlusButton.setObjectName(_fromUtf8("PlusButton"))
        self.MinusButton = QtGui.QPushButton(UsartTool)
        self.MinusButton.setGeometry(QtCore.QRect(10, 240, 61, 31))
        self.MinusButton.setObjectName(_fromUtf8("MinusButton"))
        self.ExitButton = QtGui.QPushButton(UsartTool)
        self.ExitButton.setGeometry(QtCore.QRect(70, 210, 61, 31))
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.SourceButton = QtGui.QPushButton(UsartTool)
        self.SourceButton.setGeometry(QtCore.QRect(70, 290, 61, 31))
        self.SourceButton.setObjectName(_fromUtf8("SourceButton"))
        self.FactoryButton = QtGui.QPushButton(UsartTool)
        self.FactoryButton.setGeometry(QtCore.QRect(130, 290, 61, 31))
        self.FactoryButton.setObjectName(_fromUtf8("FactoryButton"))
        self.HexSendcheckBox = QtGui.QCheckBox(UsartTool)
        self.HexSendcheckBox.setGeometry(QtCore.QRect(300, 300, 91, 21))
        self.HexSendcheckBox.setObjectName(_fromUtf8("HexSendcheckBox"))
        self.widget = QtGui.QWidget(UsartTool)
        self.widget.setGeometry(QtCore.QRect(11, 11, 181, 126))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.SerialnumLabel = QtGui.QLabel(self.widget)
        self.SerialnumLabel.setObjectName(_fromUtf8("SerialnumLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.SerialnumLabel)
        self.SerialNumComboBox = QtGui.QComboBox(self.widget)
        self.SerialNumComboBox.setObjectName(_fromUtf8("SerialNumComboBox"))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.SerialNumComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.SerialNumComboBox)
        self.DataBitsLabel = QtGui.QLabel(self.widget)
        self.DataBitsLabel.setObjectName(_fromUtf8("DataBitsLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.DataBitsLabel)
        self.DatabitsComboBox = QtGui.QComboBox(self.widget)
        self.DatabitsComboBox.setObjectName(_fromUtf8("DatabitsComboBox"))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.DatabitsComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.DatabitsComboBox)
        self.BaudRateLabel = QtGui.QLabel(self.widget)
        self.BaudRateLabel.setObjectName(_fromUtf8("BaudRateLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.BaudRateLabel)
        self.BaudRataComboBox = QtGui.QComboBox(self.widget)
        self.BaudRataComboBox.setObjectName(_fromUtf8("BaudRataComboBox"))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.BaudRataComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.BaudRataComboBox)
        self.StopBitsLabel = QtGui.QLabel(self.widget)
        self.StopBitsLabel.setObjectName(_fromUtf8("StopBitsLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.StopBitsLabel)
        self.StopBitsComboBox = QtGui.QComboBox(self.widget)
        self.StopBitsComboBox.setObjectName(_fromUtf8("StopBitsComboBox"))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.StopBitsComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.StopBitsComboBox)
        self.ParityLabel = QtGui.QLabel(self.widget)
        self.ParityLabel.setObjectName(_fromUtf8("ParityLabel"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.ParityLabel)
        self.ParityComboBox = QtGui.QComboBox(self.widget)
        self.ParityComboBox.setObjectName(_fromUtf8("ParityComboBox"))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.ParityComboBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.ParityComboBox)
        self.SwitchButton.raise_()
        self.textEdit.raise_()
        self.DataReceiveArea.raise_()
        self.DataSendArea.raise_()
        self.SendDataButton.raise_()
        self.ClearDataButton.raise_()
        self.DataToSend.raise_()
        self.HexDisCheckbox.raise_()
        self.MenuButton.raise_()
        self.PowerButton.raise_()
        self.PlusButton.raise_()
        self.MinusButton.raise_()
        self.ExitButton.raise_()
        self.SourceButton.raise_()
        self.FactoryButton.raise_()
        self.DataReceiveArea.setBuddy(self.textEdit)
        self.DataSendArea.setBuddy(self.DataToSend)
        self.SerialnumLabel.setBuddy(self.SerialNumComboBox)
        self.DataBitsLabel.setBuddy(self.DatabitsComboBox)
        self.BaudRateLabel.setBuddy(self.BaudRataComboBox)
        self.StopBitsLabel.setBuddy(self.StopBitsComboBox)
        self.ParityLabel.setBuddy(self.ParityComboBox)

        self.retranslateUi(UsartTool)
        QtCore.QMetaObject.connectSlotsByName(UsartTool)
        UsartTool.setTabOrder(self.ExitButton, self.MinusButton)
        UsartTool.setTabOrder(self.MinusButton, self.MenuButton)
        UsartTool.setTabOrder(self.MenuButton, self.PlusButton)
        UsartTool.setTabOrder(self.PlusButton, self.PowerButton)
        UsartTool.setTabOrder(self.PowerButton, self.SourceButton)
        UsartTool.setTabOrder(self.SourceButton, self.FactoryButton)
        UsartTool.setTabOrder(self.FactoryButton, self.SendDataButton)
        UsartTool.setTabOrder(self.SendDataButton, self.ClearDataButton)
        UsartTool.setTabOrder(self.ClearDataButton, self.SwitchButton)
        UsartTool.setTabOrder(self.SwitchButton, self.textEdit)
        UsartTool.setTabOrder(self.textEdit, self.HexDisCheckbox)
        UsartTool.setTabOrder(self.HexDisCheckbox, self.SerialNumComboBox)
        UsartTool.setTabOrder(self.SerialNumComboBox, self.DatabitsComboBox)
        UsartTool.setTabOrder(self.DatabitsComboBox, self.BaudRataComboBox)
        UsartTool.setTabOrder(self.BaudRataComboBox, self.StopBitsComboBox)
        UsartTool.setTabOrder(self.StopBitsComboBox, self.ParityComboBox)
        UsartTool.setTabOrder(self.ParityComboBox, self.HexSendcheckBox)
        UsartTool.setTabOrder(self.HexSendcheckBox, self.DataToSend)

    def retranslateUi(self, UsartTool):
        UsartTool.setWindowTitle(_translate("UsartTool", "Dialog", None))
        self.SwitchButton.setText(_translate("UsartTool", "打开串口", None))
        self.DataReceiveArea.setText(_translate("UsartTool", "数据接收区域：", None))
        self.DataSendArea.setText(_translate("UsartTool", "数据发送区域：", None))
        self.SendDataButton.setText(_translate("UsartTool", "发送", None))
        self.ClearDataButton.setText(_translate("UsartTool", "清除", None))
        self.HexDisCheckbox.setText(_translate("UsartTool", "HEX显示", None))
        self.MenuButton.setText(_translate("UsartTool", "Menu", None))
        self.PowerButton.setText(_translate("UsartTool", "Power", None))
        self.PlusButton.setText(_translate("UsartTool", "Plus", None))
        self.MinusButton.setText(_translate("UsartTool", "Minus", None))
        self.ExitButton.setText(_translate("UsartTool", "Exit", None))
        self.SourceButton.setText(_translate("UsartTool", "Source", None))
        self.FactoryButton.setText(_translate("UsartTool", "Factory", None))
        self.HexSendcheckBox.setText(_translate("UsartTool", "HEX发送", None))
        self.SerialnumLabel.setText(_translate("UsartTool", "串口号：", None))
        self.SerialNumComboBox.setItemText(0, _translate("UsartTool", "COM1", None))
        self.SerialNumComboBox.setItemText(1, _translate("UsartTool", "COM2", None))
        self.SerialNumComboBox.setItemText(2, _translate("UsartTool", "COM3", None))
        self.SerialNumComboBox.setItemText(3, _translate("UsartTool", "COM4", None))
        self.SerialNumComboBox.setItemText(4, _translate("UsartTool", "COM6", None))
        self.SerialNumComboBox.setItemText(5, _translate("UsartTool", "COM7", None))
        self.DataBitsLabel.setText(_translate("UsartTool", "数据位：", None))
        self.DatabitsComboBox.setItemText(0, _translate("UsartTool", "5", None))
        self.DatabitsComboBox.setItemText(1, _translate("UsartTool", "6", None))
        self.DatabitsComboBox.setItemText(2, _translate("UsartTool", "7", None))
        self.DatabitsComboBox.setItemText(3, _translate("UsartTool", "8", None))
        self.BaudRateLabel.setText(_translate("UsartTool", "波特率：", None))
        self.BaudRataComboBox.setItemText(0, _translate("UsartTool", "4800", None))
        self.BaudRataComboBox.setItemText(1, _translate("UsartTool", "9600", None))
        self.BaudRataComboBox.setItemText(2, _translate("UsartTool", "19200", None))
        self.BaudRataComboBox.setItemText(3, _translate("UsartTool", "57600", None))
        self.BaudRataComboBox.setItemText(4, _translate("UsartTool", "115200", None))
        self.StopBitsLabel.setText(_translate("UsartTool", "停止位：", None))
        self.StopBitsComboBox.setItemText(0, _translate("UsartTool", "1", None))
        self.StopBitsComboBox.setItemText(1, _translate("UsartTool", "1.5", None))
        self.StopBitsComboBox.setItemText(2, _translate("UsartTool", "2", None))
        self.ParityLabel.setText(_translate("UsartTool", "奇偶校验位：", None))
        self.ParityComboBox.setItemText(0, _translate("UsartTool", "N", None))
        self.ParityComboBox.setItemText(1, _translate("UsartTool", "O", None))
        self.ParityComboBox.setItemText(2, _translate("UsartTool", "E", None))
        self.ParityComboBox.setItemText(3, _translate("UsartTool", "M", None))
        self.ParityComboBox.setItemText(4, _translate("UsartTool", "S", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    UsartTool = QtGui.QDialog()
    ui = Ui_UsartTool()
    ui.setupUi(UsartTool)
    UsartTool.show()
    sys.exit(app.exec_())

