# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(768, 467)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 340, 745, 82))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.DataToSend = QtGui.QLineEdit(self.layoutWidget)
        self.DataToSend.setObjectName(_fromUtf8("DataToSend"))
        self.horizontalLayout_2.addWidget(self.DataToSend)
        self.SendDataButton = QtGui.QPushButton(self.layoutWidget)
        self.SendDataButton.setObjectName(_fromUtf8("SendDataButton"))
        self.horizontalLayout_2.addWidget(self.SendDataButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ExitButton = QtGui.QPushButton(self.layoutWidget)
        self.ExitButton.setObjectName(_fromUtf8("ExitButton"))
        self.verticalLayout.addWidget(self.ExitButton)
        self.KeyIndicatorA = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorA.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorA.setObjectName(_fromUtf8("KeyIndicatorA"))
        self.verticalLayout.addWidget(self.KeyIndicatorA)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.MinusButton = QtGui.QPushButton(self.layoutWidget)
        self.MinusButton.setObjectName(_fromUtf8("MinusButton"))
        self.verticalLayout_2.addWidget(self.MinusButton)
        self.KeyIndicatorB = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorB.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorB.setObjectName(_fromUtf8("KeyIndicatorB"))
        self.verticalLayout_2.addWidget(self.KeyIndicatorB)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.PlusButton = QtGui.QPushButton(self.layoutWidget)
        self.PlusButton.setObjectName(_fromUtf8("PlusButton"))
        self.verticalLayout_3.addWidget(self.PlusButton)
        self.KeyIndicatorC = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorC.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorC.setObjectName(_fromUtf8("KeyIndicatorC"))
        self.verticalLayout_3.addWidget(self.KeyIndicatorC)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.MenuButton = QtGui.QPushButton(self.layoutWidget)
        self.MenuButton.setObjectName(_fromUtf8("MenuButton"))
        self.verticalLayout_4.addWidget(self.MenuButton)
        self.KeyIndicatorD = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorD.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorD.setObjectName(_fromUtf8("KeyIndicatorD"))
        self.verticalLayout_4.addWidget(self.KeyIndicatorD)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.PowerButton = QtGui.QPushButton(self.layoutWidget)
        self.PowerButton.setObjectName(_fromUtf8("PowerButton"))
        self.verticalLayout_5.addWidget(self.PowerButton)
        self.KeyIndicatorE = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorE.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorE.setObjectName(_fromUtf8("KeyIndicatorE"))
        self.verticalLayout_5.addWidget(self.KeyIndicatorE)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.SourceButton = QtGui.QPushButton(self.layoutWidget)
        self.SourceButton.setObjectName(_fromUtf8("SourceButton"))
        self.verticalLayout_6.addWidget(self.SourceButton)
        self.KeyIndicatorF = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorF.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorF.setObjectName(_fromUtf8("KeyIndicatorF"))
        self.verticalLayout_6.addWidget(self.KeyIndicatorF)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.FactoryButton = QtGui.QPushButton(self.layoutWidget)
        self.FactoryButton.setObjectName(_fromUtf8("FactoryButton"))
        self.verticalLayout_7.addWidget(self.FactoryButton)
        self.KeyIndicatorG = QtGui.QLabel(self.layoutWidget)
        self.KeyIndicatorG.setAlignment(QtCore.Qt.AlignCenter)
        self.KeyIndicatorG.setObjectName(_fromUtf8("KeyIndicatorG"))
        self.verticalLayout_7.addWidget(self.KeyIndicatorG)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ClearDataButton = QtGui.QPushButton(self.layoutWidget)
        self.ClearDataButton.setObjectName(_fromUtf8("ClearDataButton"))
        self.verticalLayout_8.addWidget(self.ClearDataButton)
        self.HexDisCheckbox = QtGui.QCheckBox(self.layoutWidget)
        self.HexDisCheckbox.setObjectName(_fromUtf8("HexDisCheckbox"))
        self.verticalLayout_8.addWidget(self.HexDisCheckbox)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.SaveDataButton = QtGui.QPushButton(self.layoutWidget)
        self.SaveDataButton.setObjectName(_fromUtf8("SaveDataButton"))
        self.verticalLayout_9.addWidget(self.SaveDataButton)
        self.HexSendcheckBox_2 = QtGui.QCheckBox(self.layoutWidget)
        self.HexSendcheckBox_2.setObjectName(_fromUtf8("HexSendcheckBox_2"))
        self.verticalLayout_9.addWidget(self.HexSendcheckBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 741, 321))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))



        self.menuComPort = QtGui.QMenu(self.menubar)
        self.menuComPort.setObjectName(_fromUtf8("menuComPort"))
        self.menuConnect = QtGui.QMenu(self.menuComPort)
        self.menuConnect.setObjectName(_fromUtf8("ComPortConnect"))
        self.menuBaudRates = QtGui.QMenu(self.menuComPort)
        self.menuBaudRates.setObjectName(_fromUtf8("menuBaudRates"))
        self.menuData_Bits = QtGui.QMenu(self.menuComPort)
        self.menuData_Bits.setObjectName(_fromUtf8("menuData_Bits"))
        self.menuStop_Bits = QtGui.QMenu(self.menuComPort)
        self.menuStop_Bits.setObjectName(_fromUtf8("menuStop_Bits"))
        self.menuParity = QtGui.QMenu(self.menuComPort)
        self.menuParity.setObjectName(_fromUtf8("menuParity"))
        self.menuKey_Edit = QtGui.QMenu(self.menubar)
        self.menuKey_Edit.setObjectName(_fromUtf8("menuKey_Edit"))
        self.menuSelect = QtGui.QMenu(self.menubar)
        self.menuSelect.setObjectName(_fromUtf8("menuSelect"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menuComport = QtGui.QAction(MainWindow)
        self.menuComport.setObjectName(_fromUtf8("menuComport"))

        self.menuConnect = QtGui.QAction(MainWindow)
        self.menuConnect.setObjectName(_fromUtf8("menuConnect"))

        self.action4800 = QtGui.QAction(MainWindow)
        self.action4800.setCheckable(True)
        self.action4800.setObjectName(_fromUtf8("action4800"))
        self.action9600 = QtGui.QAction(MainWindow)
        self.action9600.setCheckable(True)
        self.action9600.setObjectName(_fromUtf8("action9600"))
        self.action57600 = QtGui.QAction(MainWindow)
        self.action57600.setCheckable(True)
        self.action57600.setObjectName(_fromUtf8("action57600"))
        self.action115200 = QtGui.QAction(MainWindow)
        self.action115200.setCheckable(True)
        self.action115200.setObjectName(_fromUtf8("action115200"))
        self.actionMstar_9570S = QtGui.QAction(MainWindow)
        self.actionMstar_9570S.setStatusTip(_fromUtf8("the Mstar 9570s Project"))
        self.actionMstar_9570S.setCheckable(True)
        self.actionMstar_9570S.setObjectName(_fromUtf8("actionMstar_9570S"))
        self.actionRealTek = QtGui.QAction(MainWindow)
        self.actionRealTek.setCheckable(True)
        self.actionRealTek.setStatusTip(_fromUtf8("the RelTek Project"))
        self.actionRealTek.setObjectName(_fromUtf8("actionRealTek"))
        self.actionRealTek = QtGui.QAction(MainWindow)

        self.actionKeyedit = QtGui.QAction(MainWindow)
        self.actionKeyedit.setStatusTip(_fromUtf8("Edit the Virtual Key"))
        self.actionKeyedit.setObjectName(_fromUtf8("actionKeyedit"))

        self.Textbar = QtGui.QActionGroup(self)
        self.Textbar.setObjectName("Test")
        self.Textbar.addAction(self.actionRealTek)
        self.Textbar.addAction(self.actionMstar_9570S)


        self.action5 = QtGui.QAction(MainWindow)
        self.action5.setCheckable(True)
        self.action5.setObjectName(_fromUtf8("action5"))
        self.action6 = QtGui.QAction(MainWindow)
        self.action6.setCheckable(True)
        self.action6.setObjectName(_fromUtf8("action6"))
        self.action7 = QtGui.QAction(MainWindow)
        self.action7.setCheckable(True)
        self.action7.setObjectName(_fromUtf8("action7"))
        self.action8 = QtGui.QAction(MainWindow)
        self.action8.setCheckable(True)
        self.action8.setObjectName(_fromUtf8("action8"))
        self.action1 = QtGui.QAction(MainWindow)
        self.action1.setCheckable(True)
        self.action1.setObjectName(_fromUtf8("action1"))
        self.action1_5 = QtGui.QAction(MainWindow)
        self.action1_5.setCheckable(True)
        self.action1_5.setObjectName(_fromUtf8("action1_5"))
        self.action3 = QtGui.QAction(MainWindow)
        self.action3.setCheckable(True)
        self.action3.setObjectName(_fromUtf8("action3"))
        self.actionNone = QtGui.QAction(MainWindow)
        self.actionNone.setCheckable(True)
        self.actionNone.setObjectName(_fromUtf8("actionNone"))
        self.actionOdd = QtGui.QAction(MainWindow)
        self.actionOdd.setCheckable(True)
        self.actionOdd.setObjectName(_fromUtf8("actionOdd"))
        self.actionEven = QtGui.QAction(MainWindow)
        self.actionEven.setCheckable(True)
        self.actionEven.setObjectName(_fromUtf8("actionEven"))
        self.actionMark = QtGui.QAction(MainWindow)
        self.actionMark.setCheckable(True)
        self.actionMark.setObjectName(_fromUtf8("actionMark"))
        self.actionSpace = QtGui.QAction(MainWindow)
        self.actionSpace.setCheckable(True)
        self.actionSpace.setObjectName(_fromUtf8("actionSpace"))


        self.menuBaudRates.addAction(self.action4800)
        self.menuBaudRates.addAction(self.action9600)
        self.menuBaudRates.addAction(self.action57600)
        self.menuBaudRates.addAction(self.action115200)

# the all Action group delcation
        self.BaudRateGroup = QtGui.QActionGroup(self)
        self.BaudRateGroup.setObjectName("BaudRate")
        self.BaudRateGroup.addAction(self.action4800)
        self.BaudRateGroup.addAction(self.action9600)
        self.BaudRateGroup.addAction(self.action57600)
        self.BaudRateGroup.addAction(self.action115200)


        self.menuData_Bits.addAction(self.action5)
        self.menuData_Bits.addAction(self.action6)
        self.menuData_Bits.addAction(self.action7)
        self.menuData_Bits.addAction(self.action8)

        self.DataBitGroup = QtGui.QActionGroup(self)
        self.DataBitGroup.setObjectName("DatabitGroup")
        self.DataBitGroup.addAction(self.action5)
        self.DataBitGroup.addAction(self.action6)
        self.DataBitGroup.addAction(self.action7)
        self.DataBitGroup.addAction(self.action8)

        self.menuStop_Bits.addAction(self.action1)
        self.menuStop_Bits.addAction(self.action1_5)
        self.menuStop_Bits.addAction(self.action3)

        self.StopBitBGroup = QtGui.QActionGroup(self)
        self.StopBitBGroup.setObjectName("StopBitBGroup")
        self.StopBitBGroup.addAction(self.action1)
        self.StopBitBGroup.addAction(self.action1_5)
        self.StopBitBGroup.addAction(self.action3)

        self.menuParity.addAction(self.actionNone)
        self.menuParity.addAction(self.actionOdd)
        self.menuParity.addAction(self.actionEven)
        self.menuParity.addAction(self.actionMark)
        self.menuParity.addAction(self.actionSpace)

        self.Parityroup = QtGui.QActionGroup(self)
        self.Parityroup.setObjectName("Parityroup")
        self.Parityroup.addAction(self.actionNone)
        self.Parityroup.addAction(self.actionOdd)
        self.Parityroup.addAction(self.actionEven)
        self.Parityroup.addAction(self.actionMark)
        self.Parityroup.addAction(self.actionSpace)

        self.menuComPort.addAction(self.menuComport)
        self.menuComPort.addAction(self.menuConnect)
        self.menuComPort.addAction(self.menuBaudRates.menuAction())
        self.menuComPort.addAction(self.menuData_Bits.menuAction())
        self.menuComPort.addAction(self.menuStop_Bits.menuAction())
        self.menuComPort.addAction(self.menuParity.menuAction())
        self.menuSelect.addAction(self.actionMstar_9570S)
        self.menuSelect.addAction(self.actionRealTek)
        self.menuKey_Edit.addAction(self.actionKeyedit)

        self.menubar.addAction(self.menuSelect.menuAction())
        self.menubar.addAction(self.menuComPort.menuAction())
        self.menubar.addAction(self.menuKey_Edit.menuAction())



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.SendDataButton.setText(_translate("MainWindow", "发送", None))
        self.ExitButton.setText(_translate("MainWindow", "Exit", None))
        self.KeyIndicatorA.setText(_translate("MainWindow", "W", None))
        self.MinusButton.setText(_translate("MainWindow", "Minus", None))
        self.KeyIndicatorB.setText(_translate("MainWindow", "A", None))
        self.PlusButton.setText(_translate("MainWindow", "Plus", None))
        self.KeyIndicatorC.setText(_translate("MainWindow", "D", None))
        self.MenuButton.setText(_translate("MainWindow", "Menu", None))
        self.KeyIndicatorD.setText(_translate("MainWindow", "S", None))
        self.PowerButton.setText(_translate("MainWindow", "Power", None))
        self.KeyIndicatorE.setText(_translate("MainWindow", "Z", None))
        self.SourceButton.setText(_translate("MainWindow", "Source", None))
        self.KeyIndicatorF.setText(_translate("MainWindow", "X", None))
        self.FactoryButton.setText(_translate("MainWindow", "Factory", None))
        self.KeyIndicatorG.setText(_translate("MainWindow", "C", None))
        self.ClearDataButton.setText(_translate("MainWindow", "清除", None))
        self.HexDisCheckbox.setText(_translate("MainWindow", "HEX显示", None))
        self.SaveDataButton.setText(_translate("MainWindow", "保存", None))
        self.HexSendcheckBox_2.setText(_translate("MainWindow", "HEX发送", None))
        self.menuComPort.setTitle(_translate("MainWindow", "COM Port", None))
        self.menuBaudRates.setTitle(_translate("MainWindow", "BaudRates", None))
        self.menuData_Bits.setTitle(_translate("MainWindow", "Data Bits", None))
        self.menuStop_Bits.setTitle(_translate("MainWindow", "Stop Bits", None))
        self.menuParity.setTitle(_translate("MainWindow", "Parity", None))
        self.menuKey_Edit.setTitle(_translate("MainWindow", "Key Edit", None))
        self.menuSelect.setTitle(_translate("MainWindow", "Chip Select", None))
        self.menuComport.setText(_translate("MainWindow", "ComPort", None))

        self.menuConnect.setText(_translate("MainWindow","ComPort Connect",None))

        self.action4800.setText(_translate("MainWindow", "4800", None))
        self.action9600.setText(_translate("MainWindow", "9600", None))
        self.action57600.setText(_translate("MainWindow", "57600", None))
        self.action115200.setText(_translate("MainWindow", "115200", None))
        self.actionMstar_9570S.setText(_translate("MainWindow", "Mstar", None))
        self.actionRealTek.setText(_translate("MainWindow", "RealTek", None))
        self.actionKeyedit.setText(_translate("MainWindow","Edit Virtual Key",None))
        self.action5.setText(_translate("MainWindow", "5", None))
        self.action6.setText(_translate("MainWindow", "6", None))
        self.action7.setText(_translate("MainWindow", "7", None))
        self.action8.setText(_translate("MainWindow", "8", None))
        self.action1.setText(_translate("MainWindow", "1", None))
        self.action1_5.setText(_translate("MainWindow", "1.5", None))
        self.action3.setText(_translate("MainWindow", "2", None))
        self.actionNone.setText(_translate("MainWindow", "None", None))
        self.actionOdd.setText(_translate("MainWindow", "Odd", None))
        self.actionEven.setText(_translate("MainWindow", "Even", None))
        self.actionMark.setText(_translate("MainWindow", "Mark", None))
        self.actionSpace.setText(_translate("MainWindow", "Space", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

